version: '3'
services:
  sentrifugo:
    build:
      context: .
      dockerfile: Dockerfile-sentrifugo
    ports:
      - "80:80"
      - "443:443"
    devices:
      - "/dev/tty:/dev/tty"
    links:
      - "mariadb:mariadb"
  mariadb: 
    image: iamhrishikeshpadhye/sentrifugo-live:mariadb
    ports:
      - "3306:3306"
